# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: istio-ingressgateway
#   namespace: argocd
# spec:
#   project: cluster-services-application-set
#   source:
#     chart: gateway
#     repoURL: https://istio-release.storage.googleapis.com/charts
#     targetRevision: "1.21.3" # Version of Istio  to install
#     helm:
#       releaseName: istio-ingressgateway
#       valueFiles:
#         - ../../../../../../components/infrastructure/istio-helm/values-ingress-gateway.yaml
#   destination:
#     server: "insights-euc1-blue"
#     namespace: istio-system
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
