apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Helm chart configurations
helmCharts:
- name: gateway
  repo: https://istio-release.storage.googleapis.com/charts
  version: "1.21.3"  # Specify the version of Istio you want to deploy
  releaseName: gateway
  namespace: private-gtw
  valuesFile: configs/values.yaml
