apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: sealed-secrets
  includeCRDs: true
  repo: https://bitnami-labs.github.io/sealed-secrets
  version: "2.16.1"
  releaseName: sealed-secrets
  namespace: kube-system
  valuesFile: configs/values.yaml
  valuesInline:
    fullnameOverride: sealed-secrets

patches:
- path: patches/update-deployment.yaml
  target:
    kind: Deployment
    name: sealed-secrets
