apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Helm chart configurations
helmCharts:
- name: istiod
  repo: https://istio-release.storage.googleapis.com/charts
  version: "1.21.3"  # Specify the version of Istio you want to deploy
  releaseName: istiod
  namespace: istio-system
  valuesFile: configs/values.yaml

# patches:
# - path: patches/update-deployment.yaml
#   target:
#     kind: Deployment
#     name: sealed-secrets
